name: Running Code Coverage
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        pip install pytest
        pip install coverage
        echo requirements installed
    - name: Run the tests
      run: |
          pip install -r requirements.txt
          python -m pytest --junitxml=test-reports/test-results.xml 
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
